server:
  #springboot启动端口
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候,是否允许覆盖注册
  application:
    name: miaosha
  datasource:
    #数据库连接
    url: jdbc:mysql://service-mysql:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    #使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  #配置springboot对redis的依赖
  redis:
    host: 192.168.48.128
    port: 6379
    database: 10
    #设置jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 20
